kind: Namespace
apiVersion: v1
metadata:
  name: aks
  labels:
    name: aks
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain
  namespace: aks
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  namespace: aks
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopher-deployment
  labels:
    app: gopher
  namespace: aks
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gopher
  template:
    metadata:
      labels:
        app: gopher
    spec:
      containers:
      - name: gopher
        image: patrick699/gopher:1.0.1
        ports:
        - containerPort: 8082
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-managed-disk

---
apiVersion: v1
kind: Service
metadata:
  name: gopher
  namespace: aks
  labels:
    app: gopher
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: gopher
  type: LoadBalancer