apiVersion: v1
kind: PersistentVolume
metadata:
  name: generic-pv
  namespace: frontend
  labels:
    pv : frontend
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/files"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generic-pvc
  namespace: frontend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
